### ISSUE TITLE
FuseBox Support ?

### ISSUE THREAD

**Issue by Kompwu** [ndaidong/ssr-engine#16]
> FuseBox is a blazing fast bundler/module loader, where you measure you build time in millseconds.

it'd be really nice.
That would add TypeScript support too!

**Comment by ndaidong** [comment]
@Kompwu no. This is just a small tool for lazy developers like me who love to build the traditional style websites  with modern features of JS/CSS. No Babel, nor TypeScript, nor WebPack, Parcel... Just need Rollup to handle ES6 module.

**Comment by Kompwu** [comment]
@ndaidong FuseBox IS a modern bundler. It can bundle JavaScript & TypeScript, What is especially interesting is the minification of the bundle & simplicity of configuration, in only 10 lines of code it is done!  And it's very fast, unlike Parcel.  I think it's worth it for lazy devs.

**Comment by ndaidong** [comment]
@Kompwu Never used it before. I would take a look on it.

**Comment by Kompwu** [comment]
@ndaidong You'll see, it's worth it!
I use it for heavy projects and it's very fast!
40ms on average for TypeScript + Babel + PostCSS & LESS + Pug.
Very impressive, isn't it?
