### ISSUE TITLE
WebCrawler handling ?

### ISSUE THREAD

**Issue by Kompwu** [ndaidong/ssr-engine#17]
It's a bit confusing.
Can you enlighten me?

**Comment by ndaidong** [comment]
@Kompwu what did you mean?

**Comment by Kompwu** [comment]
@ndaidong I mean DOM changes.
If my code changes the DOM, is it pre-rendered?
By example if i append something.
This can cause problems if this is not the case.

**Comment by ndaidong** [comment]
@Kompwu This is just a pre-configured version of ExpressJS. It renders HTML from Pug template files with given template data. It's different from Vue-ssr or React-ssr.

**Comment by Kompwu** [comment]
@ndaidong Meh, so there's nothing we can do about that?
Even w/ jsdom?

**Comment by ndaidong** [comment]
@Kompwu I have no idea about that for right now :)
